/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RiskIndexRouteImport } from './routes/risk/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as CustomerIndexRouteImport } from './routes/customer/index'
import { Route as ContractIndexRouteImport } from './routes/contract/index'
import { Route as BranchIndexRouteImport } from './routes/branch/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIndexRoute = RiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractIndexRoute = ContractIndexRouteImport.update({
  id: '/contract/',
  path: '/contract/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchIndexRoute = BranchIndexRouteImport.update({
  id: '/branch/',
  path: '/branch/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branch': typeof BranchIndexRoute
  '/contract': typeof ContractIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/product': typeof ProductIndexRoute
  '/risk': typeof RiskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branch': typeof BranchIndexRoute
  '/contract': typeof ContractIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/product': typeof ProductIndexRoute
  '/risk': typeof RiskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branch/': typeof BranchIndexRoute
  '/contract/': typeof ContractIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/product/': typeof ProductIndexRoute
  '/risk/': typeof RiskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branch'
    | '/contract'
    | '/customer'
    | '/overview'
    | '/product'
    | '/risk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branch'
    | '/contract'
    | '/customer'
    | '/overview'
    | '/product'
    | '/risk'
  id:
    | '__root__'
    | '/'
    | '/branch/'
    | '/contract/'
    | '/customer/'
    | '/overview/'
    | '/product/'
    | '/risk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchIndexRoute: typeof BranchIndexRoute
  ContractIndexRoute: typeof ContractIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
  ProductIndexRoute: typeof ProductIndexRoute
  RiskIndexRoute: typeof RiskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/': {
      id: '/risk/'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract/': {
      id: '/contract/'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/': {
      id: '/branch/'
      path: '/branch'
      fullPath: '/branch'
      preLoaderRoute: typeof BranchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchIndexRoute: BranchIndexRoute,
  ContractIndexRoute: ContractIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
  ProductIndexRoute: ProductIndexRoute,
  RiskIndexRoute: RiskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
